const TITLES = ['week 1', 'week 2', 'week 3', 'week 4'];

const COPY = {
  1: 'For someone like me who constantly moves to new cities, a suitcase always holds profound significance. It is the only companion I have besides my family, and it heralds every new beginning.',
  2: 'The five words I selected\u2014personal, enduring, protective, interchangeable, and secret\u2014are, in my view, the most apt for encapsulating the value of a suitcase. Consequently, I employed distinct visual approaches for each. For "secret," for instance, I sought to evoke the mystery of a telegram or Morse code; the concept of "protective" conveyed a sense of solidity and stability, so I utilized repetition to express that.',
  3: 'Everything appears more frenetic and rich; I wanted to use a compositional style that makes the imagery feel more fluid, reflecting the lifestyle of the "drifters." However, the visuals generated by the code turned out quite different from what I had envisioned\u2014perhaps the code interprets these combinations in a completely different way.',
  4: 'hey you\'re running from what you can\'t escape.come my way I\'ll put you under some kind of state.astray.so watch me hypnotize you with my eyes.make you fantasize bout me tonight.I\'m hypnotizing.'
};

const track = document.getElementById('track');
const railLeft = document.getElementById('rail-left');
const railRight = document.getElementById('rail-right');
const colLeft = document.getElementById('col-left');
const colRight = document.getElementById('col-right');
const copyEl = document.getElementById('copy');
const soundBtn = document.getElementById('sound-toggle');
const panels = Array.from(document.querySelectorAll('.panel'));

const tracks = {
  a: document.getElementById('track-a'),
  b: document.getElementById('track-b')
};

let current = 0;
let soundOn = true;
let unlocked = false;

function fillColumn(el, text) {
  el.textContent = '';
  if (!text) return;
  const lh = parseFloat(getComputedStyle(el).lineHeight) || 11;
  const n = Math.ceil(el.clientHeight / lh) + 2;
  const frag = document.createDocumentFragment();
  for (let i = 0; i < n; i++) {
    const s = document.createElement('span');
    s.textContent = text;
    frag.appendChild(s);
  }
  el.appendChild(frag);
}

function updateAudio() {
  const want = current >= 3 ? 'b' : 'a';
  for (const key of Object.keys(tracks)) {
    const t = tracks[key];
    if (key === want) {
      if (unlocked && soundOn && t.paused) {
        t.play().catch(() => {});
      }
    } else if (!t.paused) {
      t.pause();
    }
  }
}

function pauseAll() {
  for (const key of Object.keys(tracks)) {
    tracks[key].pause();
  }
}

function setCopy(week) {
  copyEl.classList.add('fading');
  setTimeout(() => {
    copyEl.textContent = COPY[week];
    copyEl.classList.remove('fading');
  }, 200);
}

function setCurrent(idx) {
  current = idx;
  track.style.transform = 'translateX(-' + idx * 25 + '%)';
  fillColumn(colLeft, idx > 0 ? TITLES[idx - 1] : '');
  fillColumn(colRight, TITLES[idx]);
  railLeft.classList.toggle('disabled', idx === 0);
  railRight.classList.toggle('disabled', idx === TITLES.length - 1);
  setCopy(idx + 1);
  updateAudio();
  const scroller = panels[idx].querySelector('.panel-scroll');
  if (scroller) scroller.focus({ preventScroll: true });
}

function goTo(idx) {
  idx = Math.max(0, Math.min(TITLES.length - 1, idx));
  if (idx !== current) setCurrent(idx);
}

railLeft.addEventListener('click', () => goTo(current - 1));
railRight.addEventListener('click', () => goTo(current + 1));
copyEl.addEventListener('click', e => e.stopPropagation());

window.addEventListener('keydown', e => {
  unlock();
  if (e.key === 'ArrowLeft') goTo(current - 1);
  if (e.key === 'ArrowRight') goTo(current + 1);
});

soundBtn.addEventListener('click', () => {
  soundOn = !soundOn;
  soundBtn.textContent = soundOn ? 'sound: on' : 'sound: off';
  if (soundOn) {
    updateAudio();
  } else {
    pauseAll();
  }
});

function unlock() {
  unlocked = true;
  updateAudio();
}

window.addEventListener('pointerdown', unlock);

document.addEventListener('visibilitychange', () => {
  if (document.hidden) {
    pauseAll();
  } else if (unlocked && soundOn) {
    updateAudio();
  }
});

window.addEventListener('resize', () => {
  fillColumn(colLeft, current > 0 ? TITLES[current - 1] : '');
  fillColumn(colRight, TITLES[current]);
});

setCurrent(0);

const finalStage = document.getElementById('final-stage');
const finalPoster = document.getElementById('w4-final-poster');
const camera = document.getElementById('w4-camera');
let camStream = null;

function startCamera() {
  if (camStream || camera.dataset.failed === '1') return;
  if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
    camera.dataset.failed = '1';
    return;
  }
  navigator.mediaDevices.getUserMedia({
    video: { width: { ideal: 1280 }, height: { ideal: 1920 } },
    audio: false
  }).then(stream => {
    camStream = stream;
    camera.srcObject = stream;
    camera.classList.add('live');
  }).catch(() => {
    camera.dataset.failed = '1';
  });
}

function stopCamera() {
  if (!camStream) return;
  camStream.getTracks().forEach(t => t.stop());
  camStream = null;
  camera.srcObject = null;
  camera.classList.remove('live');
}

const posterIO = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    finalPoster.classList.toggle('visible', entry.isIntersecting);
  });
}, { threshold: 0.25 });
posterIO.observe(finalStage);

const cameraIO = new IntersectionObserver(entries => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      startCamera();
    } else {
      stopCamera();
    }
  });
}, { rootMargin: '50% 0px 50% 0px', threshold: 0 });
cameraIO.observe(finalStage);

(() => {
  const host = document.getElementById('w4-canvas-host');
  const bg = document.getElementById('w4-bg');
  const closedEl = document.getElementById('suitcase-closed');
  const openEl = document.getElementById('suitcase-open');
  const POSTER_RATIO = 1584 / 1224;
  const ZONE = 0.15;
  const JITTER = 1.5;
  const FADE_DELAY = 500;
  const FADE_IN = 1200;
  const items = [];
  let opened = false;
  let fadeStart = 0;
  let dragIdx = -1;
  let grabX = 0;
  let grabY = 0;
  let cw = 0;
  let ch = 0;

  function clampPoster(t) {
    const x0 = cw * ZONE;
    const x1 = cw * (1 - ZONE) - t.w;
    const y0 = ch * ZONE;
    const y1 = ch * (1 - ZONE) - t.h;
    if (t.x < x0) t.x = x0;
    if (t.x > x1) t.x = x1;
    if (t.y < y0) t.y = y0;
    if (t.y > y1) t.y = y1;
  }

  closedEl.addEventListener('click', () => {
    if (opened) return;
    opened = true;
    closedEl.style.opacity = '0';
    closedEl.style.pointerEvents = 'none';
    openEl.hidden = false;
    requestAnimationFrame(() => {
      openEl.style.opacity = '1';
    });
    setTimeout(() => {
      openEl.style.opacity = '0';
    }, 1200);
    setTimeout(() => {
      openEl.hidden = true;
    }, 2200);
    const hr = host.getBoundingClientRect();
    const r = closedEl.getBoundingClientRect();
    const cx = r.left + r.width / 2 - hr.left;
    const cy = r.top + r.height / 2 - hr.top;
    const w = cw * 0.13;
    const h = w * POSTER_RATIO;
    for (const t of items) {
      t.w = w;
      t.h = h;
      t.x = cx - w / 2 + (Math.random() * 2 - 1) * w;
      t.y = cy - h / 2 + (Math.random() * 2 - 1) * h * 0.5;
      const a = Math.random() * Math.PI * 2;
      const s = 0.2 + Math.random() * 0.7;
      t.vx = Math.cos(a) * s;
      t.vy = Math.sin(a) * s;
      clampPoster(t);
    }
    for (let i = items.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const tmp = items[i];
      items[i] = items[j];
      items[j] = tmp;
    }
    fadeStart = performance.now() + FADE_DELAY;
  });

  function posterAt(p) {
    for (let i = items.length - 1; i >= 0; i--) {
      const t = items[i];
      if (p.mouseX > t.x && p.mouseX < t.x + t.w &&
        p.mouseY > t.y && p.mouseY < t.y + t.h) {
        return i;
      }
    }
    return -1;
  }

  const sketch = p => {
    p.preload = () => {
      for (let i = 1; i <= 24; i++) {
        const n = String(i).padStart(2, '0');
        items.push({
          img: p.loadImage('assets/week4/poster-' + n + '.png'),
          x: 0, y: 0, w: 0, h: 0, vx: 0, vy: 0
        });
      }
    };

    p.setup = () => {
      cw = host.clientWidth;
      ch = host.clientHeight;
      const c = p.createCanvas(cw, ch);
      c.parent(host);
      p.pixelDensity(1);
    };

    p.draw = () => {
      const hr = host.getBoundingClientRect();
      if (hr.right <= 0 || hr.left >= window.innerWidth) return;
      bg.style.transform = 'translate(' +
        ((Math.random() * 2 - 1) * JITTER).toFixed(2) + 'px,' +
        ((Math.random() * 2 - 1) * JITTER).toFixed(2) + 'px) scale(1.01)';
      p.clear();
      const alpha = opened
        ? Math.min(1, Math.max(0, (performance.now() - fadeStart) / FADE_IN))
        : 0;
      if (alpha > 0) {
        p.drawingContext.globalAlpha = alpha;
        for (let i = 0; i < items.length; i++) {
          const t = items[i];
          if (i !== dragIdx) {
            t.x += t.vx;
            t.y += t.vy;
            const x0 = cw * ZONE;
            const x1 = cw * (1 - ZONE) - t.w;
            const y0 = ch * ZONE;
            const y1 = ch * (1 - ZONE) - t.h;
            if (t.x < x0) { t.x = x0; t.vx = Math.abs(t.vx); }
            if (t.x > x1) { t.x = x1; t.vx = -Math.abs(t.vx); }
            if (t.y < y0) { t.y = y0; t.vy = Math.abs(t.vy); }
            if (t.y > y1) { t.y = y1; t.vy = -Math.abs(t.vy); }
          }
          p.image(t.img, t.x, t.y, t.w, t.h);
        }
        p.drawingContext.globalAlpha = 1;
      }
      let cur = 'default';
      if (opened && alpha > 0.5) {
        if (dragIdx >= 0) {
          cur = 'grabbing';
        } else if (posterAt(p) >= 0) {
          cur = 'grab';
        }
      }
      p.canvas.style.cursor = cur;
    };

    p.mousePressed = () => {
      if (!opened) return;
      const hit = posterAt(p);
      if (hit >= 0) {
        items.push(items.splice(hit, 1)[0]);
        dragIdx = items.length - 1;
        grabX = p.mouseX - items[dragIdx].x;
        grabY = p.mouseY - items[dragIdx].y;
        return false;
      }
    };

    p.mouseDragged = () => {
      if (dragIdx >= 0) {
        const t = items[dragIdx];
        t.x = p.mouseX - grabX;
        t.y = p.mouseY - grabY;
        clampPoster(t);
        return false;
      }
    };

    p.mouseReleased = () => {
      if (dragIdx >= 0) {
        const t = items[dragIdx];
        const a = Math.random() * Math.PI * 2;
        const s = 0.1 + Math.random() * 0.3;
        t.vx = Math.cos(a) * s;
        t.vy = Math.sin(a) * s;
        dragIdx = -1;
      }
    };

    p.windowResized = () => {
      const ow = cw;
      const oh = ch;
      cw = host.clientWidth;
      ch = host.clientHeight;
      p.resizeCanvas(cw, ch);
      const w = cw * 0.13;
      const h = w * POSTER_RATIO;
      for (const t of items) {
        t.x = t.x * cw / ow;
        t.y = t.y * ch / oh;
        t.w = w;
        t.h = h;
        clampPoster(t);
      }
    };
  };

  new p5(sketch, host);
})();
